<?php
// config/config.php
// This file will be generated by the installer.

define('DB_HOST', 'localhost');
define('DB_USER', 'hostbill_user');
define('DB_PASS', 'password');
define('DB_NAME', 'hostbill');
